Add several people from slack/github
minvws/nl-covid19-notification-app-design pull request #78
Opened 2020-08-13 10:35 UTC by dirkx

2020-08-14 11:36 UTC, jorisleker requested changes
Some questions before approving:
1. Have you checked these people agree to be mentioned here?
2. We prefer full names iso slack/twitter handles, could you check their full names?
3. line 9: bwborersma is duplicate of line 7 (Benjamin Broersma), please correct.

2020-08-15 12:14 UTC, dirkx commented
Fixed & removed BranD as I cannot find his email anywhere anymore. Re-requested ok.

2020-08-15 12:16 UTC, dirkx commented
b.t.w the person with the github handle preferred that github handle.

2020-08-15 13:34 UTC, jorisleker approved these changes

2020-08-15 13:35 UTC, merged